### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by MPurushothamRao** [tomdpotter/cg_param_m3#3]
cg_param_m3.py:110: RuntimeWarning: divide by zero encountered in true_divide
  scores = scores/np.amin(scores)
cg_param_m3.py:110: RuntimeWarning: invalid value encountered in true_divide
  scores = scores/np.amin(scores)
smarts
Traceback (most recent call last):
  File "cg_param_m3.py", line 1310, in <module>
    A_cg,beads,ring_beads,path_matrix = mapping(mol,ring_atoms,matched_maps,3)
  File "cg_param_m3.py", line 599, in mapping
    frag_results_final = postprocessing(frag_results,[],n_iter,A_frag,w_frag,path_frag,[])
  File "cg_param_m3.py", line 492, in postprocessing
    results_dict,ring_atoms,exclusion_list= path_contraction(last_iter,postprocess,A_init,w_init,ring_atoms,matched_maps,path_matrix,exclusion_list)
  File "cg_param_m3.py", line 511, in path_contraction
    groups,ring_beads,exclusion_list = lone_atom(ties,oldA,A_init,scores,ring_beads,matched_maps,comp,exclusion_list)
  File "cg_param_m3.py", line 181, in lone_atom
    test_group.extend(comp[bonded_mm[0]])
IndexError: list index out of range
I'm getting this error can u tell me what is the mistake 
Command i was used was:
cg_param_m3.py "CC(C1CCC(C(O1)OC2C(CC(C(C2O)OC3C(C(C(CO3)(C)O)NC)O)N)N)N)NC" ff.gro ff.itp 1
This is the smiles of Gentamycin 
Thank You

**Comment by EKearn** [comment]
Hi there,

Sorry we didn't notice this issue sooner! Is this using the cg_param_m3.py from the main branch of the GitHub? There's a newer version (branch martini3_V1) which works for this smiles. It reflects an old issue we had with ring atoms bearing more than one substituent. This bug is resolved in version 1 of the code, apologies it should be the default branch. Also in your run command you have the molecule's tuning function turned on (with '1' as opposed to 0). This is part of an upcoming feature currently under development. It may not be useful with your molecule. Also also, we will be moving to a broader cg_kmw, at 'https://github.com/cgkmw-durham/cg_param_m3/tree/martini3_v1' which will be the one updated going forward. Hope this helps.
